-- ==============================================================================
-- Flyway Migration V12: Question Bank & IndiaBix-Style MCQ Assessment Schema
-- Database: PostgreSQL 16 / H2 compatible
-- Project: SkillForge AI
-- ==============================================================================

-- 1. Question Bank Table
CREATE TABLE IF NOT EXISTS question_bank (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category VARCHAR(100) NOT NULL, -- Aptitude, Technical, General
    topic VARCHAR(100) NOT NULL,    -- Quantitative Aptitude, Logical Reasoning, Java, React, SQL, etc.
    subtopic VARCHAR(100),
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM', -- EASY, MEDIUM, HARD
    question_text TEXT NOT NULL,
    option_a TEXT NOT NULL,
    option_b TEXT NOT NULL,
    option_c TEXT NOT NULL,
    option_d TEXT NOT NULL,
    correct_option INT NOT NULL DEFAULT 0, -- 0=A, 1=B, 2=C, 3=D
    explanation TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_qbank_category ON question_bank(category);
CREATE INDEX IF NOT EXISTS idx_qbank_topic ON question_bank(topic);
CREATE INDEX IF NOT EXISTS idx_qbank_difficulty ON question_bank(difficulty);

-- ==============================================================================
-- Seed Data: IndiaBix-Style Question Bank (Aptitude, Technical & General MCQs)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. APTITUDE: QUANTITATIVE APTITUDE
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000001', 'Aptitude', 'Quantitative Aptitude', 'Percentages', 'EASY', 'A student scored 85 out of 100 in Math and 90 out of 120 in Science. What is the overall combined percentage?', '78.5%', '79.54%', '82.1%', '85.0%', 1, 'Total marks obtained = 85 + 90 = 175. Total maximum marks = 100 + 120 = 220. Combined Percentage = (175 / 220) * 100 = 79.54%.'),
('d1000000-0000-0000-0000-000000000002', 'Aptitude', 'Quantitative Aptitude', 'Profit & Loss', 'MEDIUM', 'A laptop is sold for $720 at a profit of 20%. What was the cost price of the laptop?', '$550', '$600', '$640', '$650', 1, 'Selling Price (SP) = Cost Price (CP) * 1.20. Therefore, CP = 720 / 1.20 = $600.'),
('d1000000-0000-0000-0000-000000000003', 'Aptitude', 'Quantitative Aptitude', 'Speed & Distance', 'MEDIUM', 'A train running at a speed of 60 km/h crosses a pole in 9 seconds. What is the length of the train in meters?', '120 m', '150 m', '180 m', '200 m', 1, 'Speed in m/s = 60 * (5/18) = 50/3 m/s. Distance = Speed * Time = (50/3) * 9 = 150 meters.'),
('d1000000-0000-0000-0000-000000000004', 'Aptitude', 'Quantitative Aptitude', 'Probability', 'HARD', 'Two fair dice are rolled simultaneously. What is the probability that the sum of the numbers is 8?', '5/36', '1/6', '7/36', '1/9', 0, 'Total outcomes = 6 * 6 = 36. Outcomes with sum 8 are (2,6), (3,5), (4,4), (5,3), (6,2) -> 5 outcomes. Probability = 5/36.'),
('d1000000-0000-0000-0000-000000000005', 'Aptitude', 'Quantitative Aptitude', 'Averages', 'EASY', 'The average score of 5 students in an assessment is 80. If a 6th student scores 98, what is the new average?', '82', '83', '84', '85', 1, 'Initial total score = 5 * 80 = 400. New total = 400 + 98 = 498. New average for 6 students = 498 / 6 = 83.');

-- ------------------------------------------------------------------------------
-- 2. APTITUDE: LOGICAL REASONING
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000010', 'Aptitude', 'Logical Reasoning', 'Number Series', 'EASY', 'Find the next number in the sequence: 3, 7, 15, 31, 63, ?', '95', '127', '128', '131', 1, 'Each term is generated by (previous * 2) + 1. (63 * 2) + 1 = 127.'),
('d1000000-0000-0000-0000-000000000011', 'Aptitude', 'Logical Reasoning', 'Coding-Decoding', 'MEDIUM', 'If "PYTHON" is coded as "QZUIPO", how is "SPRING" coded in the same pattern?', 'TQSHOH', 'TQSIOH', 'RROHMFF', 'TQRJOH', 1, 'Pattern: Shift each letter forward by +1 in the alphabet (P->Q, Y->Z, T->U, H->I, O->P, N->O). S->T, P->Q, R->S, I->J, N->O, G->H -> TQSIOH.'),
('d1000000-0000-0000-0000-000000000012', 'Aptitude', 'Logical Reasoning', 'Syllogism', 'HARD', 'Statements: "All algorithms are functions. All functions are logic." Conclusions: I. All algorithms are logic. II. Some logic are functions.', 'Only I follows', 'Only II follows', 'Both I and II follow', 'Neither follows', 2, 'By transitive property: Algorithms ⊆ Functions ⊆ Logic. Therefore, All algorithms are logic (I) is True, and Some logic are functions (II) is True.'),
('d1000000-0000-0000-0000-000000000013', 'Aptitude', 'Logical Reasoning', 'Blood Relations', 'MEDIUM', 'Pointing to a photo, Sarah said, "His mother is the only daughter of my mother." How is Sarah related to the boy in the photo?', 'Sister', 'Mother', 'Aunt', 'Grandmother', 1, 'Sarah''s mother''s only daughter is Sarah herself. Therefore, Sarah is the boy''s mother.');

-- ------------------------------------------------------------------------------
-- 3. APTITUDE: VERBAL ABILITY
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000020', 'Aptitude', 'Verbal Ability', 'Synonyms', 'EASY', 'Select the word most nearly opposite in meaning to "Meticulous":', 'Careful', 'Sloppy', 'Precise', 'Thorough', 1, '"Meticulous" means showing extreme care and precision. The antonym (opposite) is "Sloppy" or careless.'),
('d1000000-0000-0000-0000-000000000021', 'Aptitude', 'Verbal Ability', 'Sentence Correction', 'MEDIUM', 'Identify the grammatically correct sentence:', 'The team are ready for their deployment.', 'Neither the architect nor the developers was aware of the bug.', 'The manager, along with the engineers, is attending the sprint demo.', 'Each of the servers were restarted yesterday.', 2, 'When a singular subject ("manager") is joined by "along with", the verb remains singular ("is attending").'),
('d1000000-0000-0000-0000-000000000022', 'Aptitude', 'Verbal Ability', 'Vocabulary', 'MEDIUM', 'What is the meaning of the technical term "Idempotent"?', 'An operation that executes in O(1) time', 'An operation that can be applied multiple times without changing the result beyond the initial application', 'A service that automatically recovers from hardware crashes', 'A function that takes zero arguments', 1, 'Idempotence means calling an API endpoint multiple times yields the same result state as a single call (e.g. HTTP PUT/DELETE).');

-- ------------------------------------------------------------------------------
-- 4. APTITUDE: DATA INTERPRETATION
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000030', 'Aptitude', 'Data Interpretation', 'Chart Math', 'MEDIUM', 'If a tech company allocated 35% of its $2 Million budget to Cloud Infrastructure and 25% to AI R&D, how much money was spent on Cloud Infrastructure?', '$500,000', '$600,000', '$700,000', '$800,000', 2, '35% of $2,000,000 = 0.35 * 2,000,000 = $700,000.');

-- ------------------------------------------------------------------------------
-- 5. TECHNICAL: DATA STRUCTURES & ALGORITHMS
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000040', 'Technical', 'Data Structures', 'Arrays & Hash Maps', 'EASY', 'What is the worst-case time complexity for searching a key in a standard Hash Table without collision resolution optimization?', 'O(1)', 'O(log N)', 'O(N)', 'O(N^2)', 2, 'If all keys hash to the same bucket (hash collision degradation into a linked list), worst-case lookup degrades to O(N).'),
('d1000000-0000-0000-0000-000000000041', 'Technical', 'Data Structures', 'Trees', 'MEDIUM', 'In a Binary Search Tree (BST), which traversal order outputs the elements in strictly sorted ascending order?', 'Pre-order Traversal', 'In-order Traversal', 'Post-order Traversal', 'Level-order Traversal', 1, 'In-order traversal visits (Left, Root, Right), which outputs binary search tree keys in sorted ascending order.'),
('d1000000-0000-0000-0000-000000000042', 'Technical', 'Algorithms', 'Sorting', 'MEDIUM', 'Which sorting algorithm guarantees O(N log N) worst-case time complexity and operates in-place?', 'QuickSort', 'MergeSort', 'HeapSort', 'BubbleSort', 2, 'HeapSort has guaranteed O(N log N) time complexity in all cases (best, average, worst) and requires O(1) auxiliary space (in-place). MergeSort requires O(N) extra space.'),
('d1000000-0000-0000-0000-000000000043', 'Technical', 'Algorithms', 'Dynamic Programming', 'HARD', 'Which property must a problem possess for Dynamic Programming to be applicable?', 'Greedy Choice & Optimal Substructure', 'Overlapping Subproblems & Optimal Substructure', 'Divide and Conquer & Linear Time', 'Monotonicity & Binary Partitioning', 1, 'Dynamic Programming is suitable for optimization problems exhibiting Overlapping Subproblems (reusing calculated results) and Optimal Substructure.');

-- ------------------------------------------------------------------------------
-- 6. TECHNICAL: OOP CONCEPTS
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000050', 'Technical', 'OOP Concepts', 'Polymorphism', 'EASY', 'What is compile-time polymorphism in Object-Oriented Programming commonly called?', 'Method Overriding', 'Method Overloading', 'Dynamic Binding', 'Encapsulation', 1, 'Method overloading (same method name, different parameter signatures) is resolved at compile-time (static polymorphism). Method overriding is resolved at runtime.'),
('d1000000-0000-0000-0000-000000000051', 'Technical', 'OOP Concepts', 'Abstraction', 'MEDIUM', 'What is the main difference between an Abstract Class and an Interface in modern Java/C++?', 'Interfaces cannot contain default method implementations', 'A class can implement multiple interfaces, but extend only one abstract class', 'Abstract classes cannot have fields', 'Interfaces cannot be declared public', 1, 'Java supports single inheritance for classes (including abstract classes), but multiple inheritance of type via interfaces.');

-- ------------------------------------------------------------------------------
-- 7. TECHNICAL: DBMS & SQL
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000060', 'Technical', 'DBMS', 'ACID Properties', 'EASY', 'Which letter in ACID guarantees that a committed transaction will survive system failure or power loss?', 'Atomicity', 'Consistency', 'Isolation', 'Durability', 3, 'Durability ensures that once a database transaction commits, its changes are saved permanently to non-volatile storage even during power failures.'),
('d1000000-0000-0000-0000-000000000061', 'Technical', 'SQL', 'JOIN Operations', 'MEDIUM', 'Which SQL JOIN returns all rows from the left table and matching records from the right table, filling non-matching right columns with NULL?', 'INNER JOIN', 'RIGHT JOIN', 'LEFT JOIN', 'FULL OUTER JOIN', 2, 'LEFT JOIN returns all rows from the left table regardless of whether there is a match in the right table.'),
('d1000000-0000-0000-0000-000000000062', 'Technical', 'SQL', 'Window Functions', 'HARD', 'Which SQL window function ranks rows without leaving gaps in the ranking sequence when duplicate values occur?', 'RANK()', 'DENSE_RANK()', 'ROW_NUMBER()', 'NTILE()', 1, 'DENSE_RANK() assigns consecutive rank values (1, 2, 2, 3), whereas RANK() leaves gaps (1, 2, 2, 4).');

-- ------------------------------------------------------------------------------
-- 8. TECHNICAL: OPERATING SYSTEMS & COMPUTER NETWORKS
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000070', 'Technical', 'Operating Systems', 'Concurrency', 'MEDIUM', 'What is a deadlock situation in operating systems?', 'When a process terminates without releasing allocated memory', 'When two or more processes are indefinitely blocked waiting for resources held by each other', 'When CPU usage reaches 100%', 'When virtual memory runs out of page frames', 1, 'Deadlock occurs when processes hold resources and wait indefinitely for other resources held by peer processes (Circular Wait, Mutual Exclusion, Hold & Wait, No Preemption).'),
('d1000000-0000-0000-0000-000000000071', 'Technical', 'Computer Networks', 'Protocols', 'EASY', 'Which layer of the OSI model is responsible for end-to-end reliable transmission and port numbers (e.g. TCP/UDP)?', 'Network Layer (Layer 3)', 'Transport Layer (Layer 4)', 'Session Layer (Layer 5)', 'Application Layer (Layer 7)', 1, 'The Transport Layer (Layer 4) handles end-to-end communication, flow control, error checking, and port addressing (TCP/UDP).');

-- ------------------------------------------------------------------------------
-- 9. TECHNICAL: JAVA, PYTHON, JAVASCRIPT, REACT & SPRING BOOT
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000080', 'Technical', 'Java', 'Spring Framework', 'EASY', 'What Spring annotation is used to auto-wire bean dependencies by type into a constructor or field?', '@Bean', '@Autowired', '@Component', '@Service', 1, '@Autowired marks a constructor, field, or setter for automatic dependency injection by Spring IoC container.'),
('d1000000-0000-0000-0000-000000000081', 'Technical', 'Java', 'Streams API', 'MEDIUM', 'Which Java Stream terminal operation reduces elements into a single accumulated result?', 'map()', 'filter()', 'collect()', 'flatMap()', 2, 'collect() (or reduce()) is a terminal operation that transforms stream elements into a container result (e.g. List, Set, String).'),
('d1000000-0000-0000-0000-000000000082', 'Technical', 'Python', 'Decorators', 'MEDIUM', 'What is a Python decorator?', 'A function that takes another function as an argument and extends its behavior without modifying it', 'A class used for formatting string outputs', 'A special file header comment', 'A package manager extension', 0, 'Decorators wrap a function to execute code before and after the wrapped function call using the @decorator syntax.'),
('d1000000-0000-0000-0000-000000000083', 'Technical', 'JavaScript', 'Event Loop', 'MEDIUM', 'In JavaScript, which execution queue takes precedence after the call stack empties?', 'Macro-task Queue (setTimeout callbacks)', 'Micro-task Queue (Promises, process.nextTick)', 'Rendering Queue', 'Network I/O Queue', 1, 'Micro-tasks (Promises, queueMicrotask) run immediately after the current script completes before macro-tasks (setTimeout, setInterval).'),
('d1000000-0000-0000-0000-000000000084', 'Technical', 'React', 'Hooks', 'EASY', 'Which React hook handles side effects such as data fetching, subscriptions, or DOM mutations?', 'useState', 'useEffect', 'useContext', 'useReducer', 1, 'useEffect runs side effects after component rendering based on specified dependency array items.'),
('d1000000-0000-0000-0000-000000000085', 'Technical', 'Spring Boot', 'REST Controller', 'EASY', 'Which Spring Boot annotation combines @Controller and @ResponseBody to return JSON/XML directly?', '@RestController', '@Service', '@Repository', '@EnableAutoConfiguration', 0, '@RestController is a convenience annotation that annotates a controller with both @Controller and @ResponseBody.');

-- ------------------------------------------------------------------------------
-- 10. GENERAL: HR & BEHAVIORAL MCQS
-- ------------------------------------------------------------------------------
INSERT INTO question_bank (id, category, topic, subtopic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_option, explanation) VALUES
('d1000000-0000-0000-0000-000000000090', 'General', 'HR/Behavioral MCQs', 'Conflict Resolution', 'EASY', 'When faced with a disagreement with a senior team member on technical implementation strategy during a sprint, what is the best approach?', 'Ignore the team member and proceed with your own implementation', 'Publicly argue during the daily standup meeting', 'Schedule a one-on-one discussion to understand their perspective, review data/benchmarks, and find a collaborative compromise', 'Escalate immediately to upper executive management', 2, 'Professional conflict resolution involves empathetic active listening, objective data evaluation, and respectful direct communication.'),
('d1000000-0000-0000-0000-000000000091', 'General', 'HR/Behavioral MCQs', 'Time Management', 'EASY', 'What does the STAR technique stand for when answering behavioral interview questions?', 'Skill, Task, Action, Result', 'Situation, Task, Action, Result', 'Strategy, Team, Analysis, Report', 'Structure, Testing, Alignment, Review', 1, 'STAR stands for Situation, Task, Action, and Result — a structured method for framing behavioral responses.');
